# This docker-compose file can be used to run this service in standalone mode, i.e. on its own, isolated

#														#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>	#
#														#

version: "3"
services:
    metadata:
        image: identifiersorg/cloud-ws-metadata
        environment:
            - WS_METADATA_CONFIG_RESOLVER_HOST=resolver
            - WS_METADATA_CONFIG_RESOLVER_PORT=8080
        ports:
            - 8082:8082
