# This docker-compose file can be used to run this service in standalone mode, i.e. on its own, isolated
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
version: "3"
services:
    metadata:
        image: identifiersorg/cloud-ws-metadata
        environment:
            - WS_METADATA_CONFIG_RESOLVER_HOST=resolver
            - WS_METADATA_CONFIG_RESOLVER_PORT=8080
            - WS_METADATA_JVM_MEMORY_MAX=1024m
        ports:
            - "8082:8082"
        depends_on:
            - resolver
    resolver:
        image: identifiersorg/cloud-ws-resolver
        environment:
            - WS_RESOLVER_CONFIG_REDIS_HOST=redis
            - WS_RESOLVER_CONFIG_REDIS_PORT=6379
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_HOST=recommender
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_PORT=8083
            - WS_RESOLVER_JVM_MEMORY_MAX=1024m
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - recommender
    recommender:
        image: identifiersorg/cloud-ws-resource-recommender
        environment:
            - WS_RESOURCE_RECOMMENDER_JVM_MEMORY_MAX=1024m
            - WS_RESOURCE_RECOMMENDER_CONFIG_BACKEND_SERVICE_LINK_CHECKER_HOST=link-checker
        ports:
            - "8083:8083"
    redis:
        image: redis:4.0.8-alpine
        ports:
            - "6379:6379"
